// AUTO-GENERATED by scripts/generate-richtext-manifests.ts - do not edit manually.
// write tools with richtext params: 30, total tools scanned: 212
export const DUAL_WRITE_TOOLS: readonly string[] = ["tapd_create_wiki","tapd_update_wiki"];

export const WRITE_RICHTEXT_FIELDS_BY_TOOL: Record<string, readonly string[]> = {
  'tapd_create_iteration': [
    'description'
  ],
  'tapd_update_iteration': [
    'description'
  ],
  'tapd_create_story': [
    'description'
  ],
  'tapd_update_story': [
    'description'
  ],
  'tapd_create_bug': [
    'description'
  ],
  'tapd_update_bug': [
    'description'
  ],
  'tapd_create_task': [
    'description'
  ],
  'tapd_update_task': [
    'description'
  ],
  'tapd_create_comment': [
    'description'
  ],
  'tapd_update_comment': [
    'description'
  ],
  'tapd_add_module': [
    'description'
  ],
  'tapd_update_module': [
    'description'
  ],
  'tapd_add_version': [
    'description'
  ],
  'tapd_update_version': [
    'description'
  ],
  'tapd_add_feature': [
    'description'
  ],
  'tapd_update_feature': [
    'description'
  ],
  'tapd_add_baseline': [
    'description'
  ],
  'tapd_update_baseline': [
    'description'
  ],
  'tapd_add_custom_field_config': [
    'description'
  ],
  'tapd_create_test_case': [
    'description'
  ],
  'tapd_update_test_case': [
    'description'
  ],
  'tapd_create_test_plan': [
    'description'
  ],
  'tapd_update_test_plan': [
    'description'
  ],
  'tapd_create_wiki': [
    'description',
    'markdown_description'
  ],
  'tapd_update_wiki': [
    'description',
    'markdown_description'
  ],
  'tapd_create_release': [
    'description'
  ],
  'tapd_update_release': [
    'description'
  ],
  'tapd_add_launch_form': [
    'description'
  ],
  'tapd_add_board_card': [
    'description'
  ],
  'tapd_update_board_card': [
    'description'
  ]
}
;
