import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { allTools } from '../packages/core/src/tools/index.js';
import { resolveWrite } from '../packages/core/src/registry/write-policy.js';

// D8 修复（1139814312001000092）：TAPD /tapd_wikis 服务端不渲染 markdown_description，
// 这些工具的 md 入参由客户端双写：description = 渲染 HTML，markdown_description = md 原文
const DUAL_WRITE_TOOLS = ['tapd_create_wiki', 'tapd_update_wiki'];
const RICHTEXT_PARAM_FIELDS = ['description', 'markdown_description'];

const fieldsByTool: Record<string, string[]> = {};
for (const tool of allTools) {
  if (!resolveWrite(tool)) continue;
  const shape = (tool.inputSchema as { shape?: Record<string, unknown> }).shape ?? {};
  const fields = RICHTEXT_PARAM_FIELDS.filter(f => f in shape);
  if (fields.length > 0) fieldsByTool[tool.name] = fields;
}

const toolCount = allTools.length;
const writeToolCount = Object.keys(fieldsByTool).length;

const lines = [
  '// AUTO-GENERATED by scripts/generate-richtext-manifests.ts - do not edit manually.',
  `// write tools with richtext params: ${writeToolCount}, total tools scanned: ${toolCount}`,
  `export const DUAL_WRITE_TOOLS: readonly string[] = ${JSON.stringify(DUAL_WRITE_TOOLS)};`,
  '',
  'export const WRITE_RICHTEXT_FIELDS_BY_TOOL: Record<string, readonly string[]> = '
    + JSON.stringify(fieldsByTool, null, 2).replace(/"/g, "'").replace(/\n/g, '\n'),
  ';\n',
];

const outPath = fileURLToPath(new URL('../packages/core/src/registry/richtext-manifests.generated.ts', import.meta.url));
writeFileSync(outPath, lines.join('\n'));
console.log(`written ${outPath}: ${writeToolCount} write tools with richtext fields, ${DUAL_WRITE_TOOLS.length} dual-write tools`);
