import { z } from 'zod';
import type { ToolDef } from '../types.js';
import { TapdClient } from '../tapd-client.js';

export const bugTools: ToolDef[] = [
  {
    name: 'tapd_get_bugs',
    description: 'Query TAPD bugs with filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID'),
      id: z.string().optional().describe('Supports multiple IDs'),
      title: z.string().optional().describe('Bug title, supports fuzzy matching'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      severity: z.string().optional().describe('Severity, supports enum query'),
      status: z.string().optional().describe('Status, supports enum query'),
      v_status: z.string().optional().describe('Status (Chinese)'),
      label: z.string().optional().describe('Label, supports enum query'),
      iteration_id: z.string().optional().describe('Iteration ID, supports enum query'),
      module: z.string().optional().describe('Module, supports enum query'),
      current_owner: z.string().optional().describe('Current owner, supports fuzzy matching'),
      reporter: z.string().optional().describe('Reporter, supports multiple users query'),
      participator: z.string().optional().describe('Participant, supports multiple users query'),
      te: z.string().optional().describe('Tester, supports fuzzy matching'),
      de: z.string().optional().describe('Developer, supports fuzzy matching'),
      cc: z.string().optional().describe('CC person'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      in_progress_time: z.string().optional().describe('Accept time, Format: YYYY-MM-DD HH:mm'),
      resolved: z.string().optional().describe('Resolve time, Format: YYYY-MM-DD HH:mm'),
      verify_time: z.string().optional().describe('Verify time, Format: YYYY-MM-DD HH:mm'),
      closed: z.string().optional().describe('Close time, Format: YYYY-MM-DD HH:mm'),
      reject_time: z.string().optional().describe('Reject time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Last modification time, Format: YYYY-MM-DD HH:mm'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      deadline: z.string().optional().describe('Resolve deadline, Format: YYYY-MM-DD'),
      release_id: z.string().optional().describe('Release plan'),
      version_report: z.string().optional().describe('Found version, enum query'),
      version_test: z.string().optional().describe('Verify version'),
      version_fix: z.string().optional().describe('Fix version'),
      version_close: z.string().optional().describe('Close version'),
      baseline_find: z.string().optional().describe('Found baseline'),
      baseline_join: z.string().optional().describe('Join baseline'),
      baseline_test: z.string().optional().describe('Test baseline'),
      baseline_close: z.string().optional().describe('Close baseline'),
      feature: z.string().optional().describe('Feature'),
      source: z.string().optional().describe('Bug root cause, supports enum query'),
      bugtype: z.string().optional().describe('Bug type'),
      frequency: z.string().optional().describe('Reproduction frequency, supports enum query'),
      originphase: z.string().optional().describe('Found phase'),
      sourcephase: z.string().optional().describe('Introduction phase'),
      resolution: z.string().optional().describe('Resolution method, supports enum query'),
      description: z.string().optional().describe('Detailed description, supports fuzzy matching'),
      os: z.string().optional().describe('Operating system'),
      platform: z.string().optional().describe('Software platform'),
      testmode: z.string().optional().describe('Test mode'),
      testphase: z.string().optional().describe('Test phase'),
      testtype: z.string().optional().describe('Test type'),
      size: z.string().optional().describe('Size'),
      estimate: z.number().optional().describe('Estimated resolve time'),
      limit: z.number().optional().describe('Return count, default 30, max 200'),
      page: z.number().optional().describe('Page number, default 1'),
      order: z.string().optional().describe('Sort order'),
      fields: z.string().optional().describe('Specify return fields'),
    }),
    handler: async (client, params) => {
      return client.get('/bugs', params);
    },
  },
  {
    name: 'tapd_create_bug',
    description: 'Create a new bug in TAPD',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      title: z.string().describe('Bug title (required)'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      severity: z.string().optional().describe('Severity'),
      current_owner: z.string().optional().describe('Current owner (defaults to TAPD_NICK_NAME env)'),
      description: z.string().optional().describe('Detailed description'),
      module: z.string().optional().describe('Module'),
      iteration_id: z.string().optional().describe('Iteration ID'),
      label: z.string().optional().describe('Label, multiple values separated by |'),
      effort: z.number().optional().describe('Estimated effort'),
      template_id: z.string().optional().describe('Template ID'),
      cc: z.string().optional().describe('CC person'),
      te: z.string().optional().describe('Tester'),
      de: z.string().optional().describe('Developer'),
      reporter: z.string().optional().describe('Reporter'),
      participator: z.string().optional().describe('Participant'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      deadline: z.string().optional().describe('Resolve deadline, Format: YYYY-MM-DD'),
      release_id: z.string().optional().describe('Release plan'),
      version_report: z.string().optional().describe('Found version'),
      version_test: z.string().optional().describe('Verify version'),
      version_fix: z.string().optional().describe('Fix version'),
      version_close: z.string().optional().describe('Close version'),
      baseline_find: z.string().optional().describe('Found baseline'),
      baseline_join: z.string().optional().describe('Join baseline'),
      baseline_test: z.string().optional().describe('Test baseline'),
      baseline_close: z.string().optional().describe('Close baseline'),
      feature: z.string().optional().describe('Feature'),
      source: z.string().optional().describe('Bug root cause'),
      bugtype: z.string().optional().describe('Bug type'),
      frequency: z.string().optional().describe('Reproduction frequency'),
      originphase: z.string().optional().describe('Found phase'),
      sourcephase: z.string().optional().describe('Introduction phase'),
      resolution: z.string().optional().describe('Resolution method'),
      os: z.string().optional().describe('Operating system'),
      platform: z.string().optional().describe('Software platform'),
      testmode: z.string().optional().describe('Test mode'),
      testphase: z.string().optional().describe('Test phase'),
      testtype: z.string().optional().describe('Test type'),
      size: z.string().optional().describe('Size'),
      estimate: z.number().optional().describe('Estimated resolve time'),
    }),
    handler: async (client, params) => {
      const nickName = TapdClient.getNickName();
      const finalParams = {
        ...params,
        current_owner: params.current_owner ?? nickName,
        reporter: params.reporter ?? nickName,
      };
      return client.post('/bugs', finalParams);
    },
  },
  {
    name: 'tapd_update_bug',
    description: 'Update an existing bug in TAPD',
    inputSchema: z.object({
      id: z.string().describe('Bug ID (required)'),
      workspace_id: z.number().describe('Project ID (required)'),
      title: z.string().optional().describe('Bug title'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      severity: z.string().optional().describe('Severity'),
      status: z.string().optional().describe('Status'),
      current_owner: z.string().optional().describe('Current owner'),
      description: z.string().optional().describe('Detailed description'),
      module: z.string().optional().describe('Module'),
      iteration_id: z.string().optional().describe('Iteration ID'),
      label: z.string().optional().describe('Label, multiple values separated by |'),
      effort: z.number().optional().describe('Estimated effort'),
      cc: z.string().optional().describe('CC person'),
      te: z.string().optional().describe('Tester'),
      de: z.string().optional().describe('Developer'),
      reporter: z.string().optional().describe('Reporter'),
      participator: z.string().optional().describe('Participant'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      deadline: z.string().optional().describe('Resolve deadline, Format: YYYY-MM-DD'),
      release_id: z.string().optional().describe('Release plan'),
      version_report: z.string().optional().describe('Found version'),
      version_test: z.string().optional().describe('Verify version'),
      version_fix: z.string().optional().describe('Fix version'),
      version_close: z.string().optional().describe('Close version'),
      baseline_find: z.string().optional().describe('Found baseline'),
      baseline_join: z.string().optional().describe('Join baseline'),
      baseline_test: z.string().optional().describe('Test baseline'),
      baseline_close: z.string().optional().describe('Close baseline'),
      feature: z.string().optional().describe('Feature'),
      source: z.string().optional().describe('Bug root cause'),
      bugtype: z.string().optional().describe('Bug type'),
      frequency: z.string().optional().describe('Reproduction frequency'),
      originphase: z.string().optional().describe('Found phase'),
      sourcephase: z.string().optional().describe('Introduction phase'),
      resolution: z.string().optional().describe('Resolution method'),
      os: z.string().optional().describe('Operating system'),
      platform: z.string().optional().describe('Software platform'),
      testmode: z.string().optional().describe('Test mode'),
      testphase: z.string().optional().describe('Test phase'),
      testtype: z.string().optional().describe('Test type'),
      size: z.string().optional().describe('Size'),
      estimate: z.number().optional().describe('Estimated resolve time'),
    }),
    handler: async (client, params) => {
      return client.post('/bugs', params);
    },
  },
  {
    name: 'tapd_get_bug_count',
    description: 'Get the count of bugs matching filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      id: z.string().optional().describe('Supports multiple IDs'),
      title: z.string().optional().describe('Bug title, supports fuzzy matching'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      severity: z.string().optional().describe('Severity, supports enum query'),
      status: z.string().optional().describe('Status, supports enum query'),
      v_status: z.string().optional().describe('Status (Chinese)'),
      label: z.string().optional().describe('Label, supports enum query'),
      iteration_id: z.string().optional().describe('Iteration ID, supports enum query'),
      module: z.string().optional().describe('Module, supports enum query'),
      current_owner: z.string().optional().describe('Current owner, supports fuzzy matching'),
      reporter: z.string().optional().describe('Reporter, supports multiple users query'),
      participator: z.string().optional().describe('Participant, supports multiple users query'),
      te: z.string().optional().describe('Tester, supports fuzzy matching'),
      de: z.string().optional().describe('Developer, supports fuzzy matching'),
      cc: z.string().optional().describe('CC person'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      in_progress_time: z.string().optional().describe('Accept time, Format: YYYY-MM-DD HH:mm'),
      resolved: z.string().optional().describe('Resolve time, Format: YYYY-MM-DD HH:mm'),
      verify_time: z.string().optional().describe('Verify time, Format: YYYY-MM-DD HH:mm'),
      closed: z.string().optional().describe('Close time, Format: YYYY-MM-DD HH:mm'),
      reject_time: z.string().optional().describe('Reject time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Last modification time, Format: YYYY-MM-DD HH:mm'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      deadline: z.string().optional().describe('Resolve deadline, Format: YYYY-MM-DD'),
      release_id: z.string().optional().describe('Release plan'),
      version_report: z.string().optional().describe('Found version, enum query'),
      version_test: z.string().optional().describe('Verify version'),
      version_fix: z.string().optional().describe('Fix version'),
      version_close: z.string().optional().describe('Close version'),
      baseline_find: z.string().optional().describe('Found baseline'),
      baseline_join: z.string().optional().describe('Join baseline'),
      baseline_test: z.string().optional().describe('Test baseline'),
      baseline_close: z.string().optional().describe('Close baseline'),
      feature: z.string().optional().describe('Feature'),
      source: z.string().optional().describe('Bug root cause, supports enum query'),
      bugtype: z.string().optional().describe('Bug type'),
      frequency: z.string().optional().describe('Reproduction frequency, supports enum query'),
      originphase: z.string().optional().describe('Found phase'),
      sourcephase: z.string().optional().describe('Introduction phase'),
      resolution: z.string().optional().describe('Resolution method, supports enum query'),
      description: z.string().optional().describe('Detailed description, supports fuzzy matching'),
      os: z.string().optional().describe('Operating system'),
      platform: z.string().optional().describe('Software platform'),
      testmode: z.string().optional().describe('Test mode'),
      testphase: z.string().optional().describe('Test phase'),
      testtype: z.string().optional().describe('Test type'),
      size: z.string().optional().describe('Size'),
      estimate: z.number().optional().describe('Estimated resolve time'),
    }),
    handler: async (client, params) => {
      return client.get('/bugs/count', params);
    },
  },
];
