import { z } from 'zod';
import type { ToolDef } from '../types.js';
import { TapdClient } from '../tapd-client.js';

export const storyTools: ToolDef[] = [
  {
    name: 'tapd_get_stories',
    description: 'Query TAPD stories with filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID'),
      id: z.string().optional().describe('Supports multiple IDs'),
      name: z.string().optional().describe('Story title, supports fuzzy matching'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      status: z.string().optional().describe('Status, supports enum query'),
      v_status: z.string().optional().describe('Status (Chinese)'),
      with_v_status: z.string().optional().describe('Set to 1 to return Chinese status'),
      label: z.string().optional().describe('Label, supports enum query'),
      workitem_type_id: z.string().optional().describe('Story category ID, supports enum query'),
      owner: z.string().optional().describe('Owner, supports fuzzy matching'),
      creator: z.string().optional().describe('Creator, supports multiple users query'),
      developer: z.string().optional().describe('Developer'),
      cc: z.string().optional().describe('CC person, supports fuzzy matching'),
      iteration_id: z.string().optional().describe('Iteration ID, supports enum query'),
      include_sub_iteration: z.string().optional().describe('Include sub-iteration, 0 or 1, default 0'),
      category_id: z.string().optional().describe('Story category, supports enum query'),
      include_sub_category: z.string().optional().describe('Include sub-category, 0 or 1, default 0'),
      parent_id: z.string().optional().describe('Parent story ID'),
      ancestor_id: z.string().optional().describe('Ancestor story ID, query all child stories'),
      children_id: z.string().optional().describe('Child story ID'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Modification time, Format: YYYY-MM-DD HH:mm'),
      completed: z.string().optional().describe('Completion time, Format: YYYY-MM-DD HH:mm'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      release_id: z.string().optional().describe('Release plan'),
      module: z.string().optional().describe('Module'),
      feature: z.string().optional().describe('Feature'),
      version: z.string().optional().describe('Version'),
      source: z.string().optional().describe('Story source'),
      type: z.string().optional().describe('Story type'),
      description: z.string().optional().describe('Detailed description, supports fuzzy matching'),
      limit: z.number().optional().describe('Return count, default 30, max 200'),
      page: z.number().optional().describe('Page number, default 1'),
      order: z.string().optional().describe('Sort order'),
      fields: z.string().optional().describe('Specify return fields'),
    }),
    handler: async (client, params) => {
      return client.get('/stories', params);
    },
  },
  {
    name: 'tapd_create_story',
    description: 'Create a new story in TAPD',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      name: z.string().describe('Story name (required)'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      description: z.string().optional().describe('Detailed description'),
      owner: z.string().optional().describe('Owner (defaults to TAPD_NICK_NAME env)'),
      creator: z.string().optional().describe('Creator (defaults to TAPD_NICK_NAME env)'),
      developer: z.string().optional().describe('Developer'),
      cc: z.string().optional().describe('CC person'),
      iteration_id: z.string().optional().describe('Iteration ID'),
      category_id: z.string().optional().describe('Story category'),
      parent_id: z.string().optional().describe('Parent story ID'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      effort: z.string().optional().describe('Estimated effort'),
      release_id: z.string().optional().describe('Release plan'),
      module: z.string().optional().describe('Module'),
      feature: z.string().optional().describe('Feature'),
      version: z.string().optional().describe('Version'),
      source: z.string().optional().describe('Story source'),
      type: z.string().optional().describe('Story type'),
      label: z.string().optional().describe('Label'),
      template_id: z.string().optional().describe('Template ID'),
    }),
    handler: async (client, params) => {
      const nickName = TapdClient.getNickName();
      const finalParams = {
        ...params,
        owner: params.owner ?? nickName,
        creator: params.creator ?? nickName,
      };
      return client.post('/stories', finalParams);
    },
  },
  {
    name: 'tapd_update_story',
    description: 'Update an existing story in TAPD',
    inputSchema: z.object({
      id: z.string().describe('Story ID (required)'),
      workspace_id: z.number().describe('Project ID (required)'),
      name: z.string().optional().describe('Story name'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      description: z.string().optional().describe('Detailed description'),
      owner: z.string().optional().describe('Owner'),
      developer: z.string().optional().describe('Developer'),
      cc: z.string().optional().describe('CC person'),
      iteration_id: z.string().optional().describe('Iteration ID'),
      category_id: z.string().optional().describe('Story category'),
      parent_id: z.string().optional().describe('Parent story ID'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      release_id: z.string().optional().describe('Release plan'),
      module: z.string().optional().describe('Module'),
      feature: z.string().optional().describe('Feature'),
      version: z.string().optional().describe('Version'),
      source: z.string().optional().describe('Story source'),
      type: z.string().optional().describe('Story type'),
      label: z.string().optional().describe('Label'),
      status: z.string().optional().describe('Status'),
    }),
    handler: async (client, params) => {
      return client.post('/stories', params);
    },
  },
  {
    name: 'tapd_get_story_count',
    description: 'Get the count of stories matching filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      id: z.string().optional().describe('Supports multiple IDs'),
      name: z.string().optional().describe('Story title, supports fuzzy matching'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      status: z.string().optional().describe('Status, supports enum query'),
      v_status: z.string().optional().describe('Status (Chinese)'),
      with_v_status: z.string().optional().describe('Set to 1 to return Chinese status'),
      label: z.string().optional().describe('Label, supports enum query'),
      workitem_type_id: z.string().optional().describe('Story category ID, supports enum query'),
      owner: z.string().optional().describe('Owner, supports fuzzy matching'),
      creator: z.string().optional().describe('Creator, supports multiple users query'),
      developer: z.string().optional().describe('Developer'),
      cc: z.string().optional().describe('CC person, supports fuzzy matching'),
      iteration_id: z.string().optional().describe('Iteration ID, supports enum query'),
      include_sub_iteration: z.string().optional().describe('Include sub-iteration, 0 or 1, default 0'),
      category_id: z.string().optional().describe('Story category, supports enum query'),
      include_sub_category: z.string().optional().describe('Include sub-category, 0 or 1, default 0'),
      parent_id: z.string().optional().describe('Parent story ID'),
      ancestor_id: z.string().optional().describe('Ancestor story ID, query all child stories'),
      children_id: z.string().optional().describe('Child story ID'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Modification time, Format: YYYY-MM-DD HH:mm'),
      completed: z.string().optional().describe('Completion time, Format: YYYY-MM-DD HH:mm'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      release_id: z.string().optional().describe('Release plan'),
      module: z.string().optional().describe('Module'),
      feature: z.string().optional().describe('Feature'),
      version: z.string().optional().describe('Version'),
      source: z.string().optional().describe('Story source'),
      type: z.string().optional().describe('Story type'),
      description: z.string().optional().describe('Detailed description, supports fuzzy matching'),
    }),
    handler: async (client, params) => {
      return client.get('/stories/count', params);
    },
  },
];
