import { z } from 'zod';
import type { ToolDef } from '../types.js';
import { TapdClient } from '../tapd-client.js';

export const taskTools: ToolDef[] = [
  {
    name: 'tapd_get_tasks',
    description: 'Query TAPD tasks with filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID'),
      id: z.string().optional().describe('Supports multiple IDs'),
      name: z.string().optional().describe('Task title, supports fuzzy matching'),
      description: z.string().optional().describe('Detailed description'),
      status: z.string().optional().describe('Status, supports enum query'),
      label: z.string().optional().describe('Label, supports enum query'),
      owner: z.string().optional().describe('Owner, supports fuzzy matching'),
      creator: z.string().optional().describe('Creator, supports multiple users query'),
      cc: z.string().optional().describe('CC person'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      story_id: z.string().optional().describe('Related story ID, supports multiple IDs'),
      iteration_id: z.number().optional().describe('Iteration ID, supports enum query'),
      progress: z.number().optional().describe('Progress'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Modification time, Format: YYYY-MM-DD HH:mm'),
      completed: z.string().optional().describe('Completion time, Format: YYYY-MM-DD HH:mm'),
      limit: z.number().optional().describe('Return count, default 30, max 200'),
      page: z.number().optional().describe('Page number, default 1'),
      order: z.string().optional().describe('Sort order'),
      fields: z.string().optional().describe('Specify return fields'),
    }),
    handler: async (client, params) => {
      return client.get('/tasks', params);
    },
  },
  {
    name: 'tapd_create_task',
    description: 'Create a new task in TAPD',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      name: z.string().optional().describe('Task name'),
      description: z.string().optional().describe('Detailed description'),
      owner: z.string().optional().describe('Owner (defaults to TAPD_NICK_NAME env)'),
      creator: z.string().optional().describe('Creator'),
      cc: z.string().optional().describe('CC person'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      story_id: z.number().optional().describe('Related story ID'),
      iteration_id: z.number().optional().describe('Iteration ID'),
      status: z.string().optional().describe('Status (open, progressing, done)'),
      progress: z.number().optional().describe('Progress'),
      effort: z.string().optional().describe('Estimated effort'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      label: z.string().optional().describe('Label'),
    }),
    handler: async (client, params) => {
      const finalParams = {
        ...params,
        owner: params.owner ?? TapdClient.getNickName(),
      };
      return client.post('/tasks', finalParams);
    },
  },
  {
    name: 'tapd_update_task',
    description: 'Update an existing task in TAPD',
    inputSchema: z.object({
      id: z.string().describe('Task ID (required)'),
      workspace_id: z.number().describe('Project ID (required)'),
      name: z.string().optional().describe('Task name'),
      description: z.string().optional().describe('Detailed description'),
      owner: z.string().optional().describe('Owner'),
      cc: z.string().optional().describe('CC person'),
      priority: z.string().optional().describe('Priority'),
      priority_label: z.string().optional().describe('Priority label (recommended)'),
      story_id: z.number().optional().describe('Related story ID'),
      iteration_id: z.number().optional().describe('Iteration ID'),
      status: z.string().optional().describe('Status (open, progressing, done)'),
      progress: z.number().optional().describe('Progress'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      label: z.string().optional().describe('Label'),
    }),
    handler: async (client, params) => {
      return client.post('/tasks', params);
    },
  },
  {
    name: 'tapd_get_task_count',
    description: 'Get the count of tasks matching filters',
    inputSchema: z.object({
      workspace_id: z.number().describe('Project ID (required)'),
      id: z.string().optional().describe('Supports multiple IDs'),
      name: z.string().optional().describe('Task title, supports fuzzy matching'),
      description: z.string().optional().describe('Detailed description'),
      status: z.string().optional().describe('Status, supports enum query'),
      label: z.string().optional().describe('Label, supports enum query'),
      owner: z.string().optional().describe('Owner, supports fuzzy matching'),
      creator: z.string().optional().describe('Creator, supports multiple users query'),
      cc: z.string().optional().describe('CC person'),
      priority: z.string().optional().describe('Priority, recommend using priority_label'),
      priority_label: z.string().optional().describe('Priority (recommended)'),
      story_id: z.string().optional().describe('Related story ID, supports multiple IDs'),
      iteration_id: z.number().optional().describe('Iteration ID, supports enum query'),
      progress: z.number().optional().describe('Progress'),
      effort: z.string().optional().describe('Estimated effort'),
      effort_completed: z.string().optional().describe('Completed effort'),
      remain: z.number().optional().describe('Remaining effort'),
      exceed: z.number().optional().describe('Exceeded effort'),
      begin: z.string().optional().describe('Estimated start date, Format: YYYY-MM-DD'),
      due: z.string().optional().describe('Estimated end date, Format: YYYY-MM-DD'),
      created: z.string().optional().describe('Creation time, Format: YYYY-MM-DD HH:mm'),
      modified: z.string().optional().describe('Modification time, Format: YYYY-MM-DD HH:mm'),
      completed: z.string().optional().describe('Completion time, Format: YYYY-MM-DD HH:mm'),
    }),
    handler: async (client, params) => {
      return client.get('/tasks/count', params);
    },
  },
];
